---
- hosts: all
  become: yes
  tasks:
      - name: link /mos -> /vagrant
        file: src=/vagrant
              dest=/mos
              state=link

      # update / install packages
      - name: "Install packages"
        apt:
          update_cache: yes
          cache_valid_time: 3600
          name: "{{ item }}"
        with_items:
          - build-essential
          - python3-pip
          - python-pip
          - locales
          - python-dev
      - name: "add locale de_DE.UTF-8"
        locale_gen: name="de_DE.UTF-8" state=present
      # install required python modules
      - name: "Install python modules"
        pip: requirements={{item}} executable=pip
        with_items:
          - /vagrant/requirements.txt
          - /vagrant/requirements-dev.txt

      # check the existence of the secret_key.py file and create one if it does not exist
      # a generated file should contain something like: SECRET_KEY='<KVPy@&pwCO[1KCz.O[]*mZ\+Q*CfTTm#;$1Bdd_17gq@9dzaG'
      - stat: path=/mos/mos/settings/secret_key.py
        register: st
      - shell: echo "SECRET_KEY='`cat /dev/urandom | tr -dc 'a-z0-9!@#$%^&*(-_=+)' | head -c50`'" > /mos/mos/settings/secret_key.py
        when: st.stat.exists == False

      # prepare MOS itself
      - stat: path=/mos/mos.sqlite
        register: st_sqlite
        
      - name: django syncdb
        django_manage: app_path=/mos
                       command=syncdb
      - name: django migrate
        django_manage: app_path=/mos
                       command=migrate

      - django_manage: app_path=/mos
                       command="createsuperuser --noinput --username=admin --email=admin@example.com" 
        when: st_sqlite.stat.exists == False

      - name: django loaddata 
        django_manage: app_path=/mos 
                       fixtures='core/fixtures/default_choices.json members/fixtures/default_choices.json members/fixtures/dummy_members.json cal/fixtures/events_2012-09-20.json'
                       command=loaddata 
                       
      # If calender data fixture fails because of auth.user 1 not there. Creating Admin failed...
      # Delete mos.sqlite DB in folder and provision vagrant Box again.

      # set the default directory to /mos
      - lineinfile: dest=/home/vagrant/.bashrc
                    line='cd /mos'
