# Generated by Django 3.2.16 on 2022-11-25 21:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='advertise',
            field=models.BooleanField(default=False),
        ),
    ]
