# Generated by Django 3.2.20 on 2024-02-24 15:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_event_advertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='advertise',
            field=models.BooleanField(default=True),
        ),
    ]
