# Generated by Django 4.2.18 on 2025-11-23 13:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0003_alter_event_advertise"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="wikiImagePage",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
