# Generated by Django 3.2.20 on 2024-02-24 13:54

from django.db import migrations
from django.db import models

import things.models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='token',
            field=models.CharField(default=things.models.make_token, max_length=128),
        ),
        migrations.AlterField(
            model_name='thing',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
