# Generated by Django 3.2.20 on 2024-02-24 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('things', '0002_auto_20240224_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='thinguser',
            name='best_before',
            field=models.DateField(blank=True, help_text='Wann die Schulung wiederholt werden sollte', null=True),
        ),
        migrations.AddField(
            model_name='thinguser',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thinguser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thingusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
