# Generated by Django 3.2.20 on 2024-03-09 21:15

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0007_alter_thingevent_usage_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingevent',
            name='kind',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('USAGE_MEMBER', 'Zeit (Member)'), ('USAGE_NONMEMBER', 'Zeit (Nicht-Member)'), ('USAGE_METALAB', 'Zeit (für Metalab)')], db_index=True, max_length=32),
        ),
    ]
