# Generated by Django 4.2.18 on 2025-11-22 16:16

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0008_alter_thingevent_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="thing",
            name="expiry_notice",
            field=models.TextField(
                default="",
                help_text="Expiry notice text sent with the expiry notice email",
            ),
        ),
    ]
