# Generated by Django 3.2.16 on 2022-11-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindofmembership',
            name='spind',
            field=models.CharField(blank=True, choices=[('small_1', '1 kleiner Spind'), ('small_2', '2 kleiner Spind'), ('big_1', '1 großer Spind')], max_length=7, null=True),
        ),
    ]
