# Generated by Django 3.2.16 on 2022-11-12 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20221112_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindofmembership',
            name='fee_category',
            field=models.CharField(choices=[('standard', 'standard'), ('free', 'free'), ('decreased', 'ermäßigt'), ('increased', 'erhöht')], default='standard', max_length=9),
        ),
        migrations.AlterField(
            model_name='kindofmembership',
            name='spind',
            field=models.CharField(choices=[('no', '0 Spind'), ('small_1', '1 kleiner Spind'), ('big_1', '1 großer Spind'), ('small_2', '2 kleiner Spind')], default='no', max_length=7),
        ),
    ]
