# Generated by Django 3.2.16 on 2022-11-12 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20221112_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='key_id',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('\\b[0-9]{2}-[0-9a-zA-Z]{12}\\b', 'iButton ID entspricht nicht dem Format [0-9]{2}-[0-9a-zA-Z]{12}')]),
        ),
        migrations.AlterField(
            model_name='kindofmembership',
            name='spind',
            field=models.CharField(choices=[('no', '0 Spind (0€)'), ('small_1', '1 kleiner Spind (8€)'), ('big_1', '1 großer Spind (10€)'), ('small_2', '2 kleiner Spind (16€)')], default='no', max_length=7),
        ),
    ]
