# Generated by Django 3.2.16 on 2022-11-12 19:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20221112_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailinglistMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('on_intern_list', models.BooleanField(default=True)),
            ],
        ),
    ]
