# Generated by Django 3.2.16 on 2022-11-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_mailinglistmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='last_email_ok',
            field=models.BooleanField(null=True),
        ),
    ]
