# Generated by Django 3.2.20 on 2023-07-08 21:06

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_pendingpayment_original_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='bank_account_iban',
            field=models.CharField(blank=True, max_length=34, validators=[members.models.iban_validate]),
        ),
    ]
