# Generated by Django 3.2.20 on 2023-07-09 01:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0010_alter_paymentinfo_bank_account_iban'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recievable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=200, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recievables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
