# Generated by Django 3.2.20 on 2023-07-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_locker'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankImportMatcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matcher', models.CharField(max_length=80)),
                ('comment', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('drop', 'drop'), ('do_not_match', 'do not match'), ('color', 'color')], max_length=20)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
