# Generated by Django 3.2.20 on 2023-07-09 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0013_alter_bankimportmatcher_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankimportmatcher',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankimportmatcher',
            name='action',
            field=models.CharField(choices=[('drop', 'drop'), ('do_not_match', 'do not match'), ('match_to', 'match to'), ('color', 'color')], max_length=20),
        ),
    ]
