# Generated by Django 3.2.20 on 2023-07-09 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0014_auto_20230709_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankimportmatcher',
            name='color',
            field=models.CharField(blank=True, help_text="if action=color, e.g. 'red' or 'rgba(255,0,0,0.1)'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankimportmatcher',
            name='matcher',
            field=models.CharField(help_text='match in IBAN, sender, text', max_length=80),
        ),
        migrations.AlterField(
            model_name='bankimportmatcher',
            name='member',
            field=models.ForeignKey(blank=True, help_text='if action=match_to', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
