# Generated by Django 3.2.20 on 2024-02-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20230709_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipperiod',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
