# Generated by Django 3.2.20 on 2024-02-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20230709_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='has_lazzzor_privileges',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='lazzzor_rate',
        ),
    ]
