# Generated by Django 3.2.20 on 2024-02-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20240224_1348'),
        ('members', '0016_membershipperiod_comment'),
    ]

    operations = [
    ]
