# Generated by Django 4.2.18 on 2025-02-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0017_merge_20240224_1514"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentinfo",
            name="bank_account_number",
        ),
        migrations.RemoveField(
            model_name="paymentinfo",
            name="bank_code",
        ),
    ]
