# Generated by Django 4.2.18 on 2025-02-01 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("members", "0018_remove_paymentinfo_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingpayment",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_pending_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
