# Generated by Django 4.2.10 on 2025-02-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_communicationrecord_monthly_fee_at_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='gdpr_wiped_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
