# Generated by Django 4.2.10 on 2025-10-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_communicationrecord_monthly_fee_at_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='in_intern_matrix_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='matrix_handle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
