# Generated by Django 4.2.18 on 2025-11-22 18:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0022_contactinfo_in_intern_matrix_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="gdpr_wiped_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
