# Generated by Django 4.2.18 on 2025-11-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0023_contactinfo_gdpr_wiped_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kindofmembership",
            options={"ordering": ["name"]},
        ),
    ]
