# Generated by Django 4.2.18 on 2025-11-23 14:37

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0024_alter_kindofmembership_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="matrix_handle",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\A@[a-z0-9_.-]+:[a-z0-9_.-]+\\Z"
                    )
                ],
            ),
        ),
    ]
