# Generated by Django 4.2.30 on 2026-06-21 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0025_alter_contactinfo_matrix_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="matrix_handle",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\A@[^:\\x00]+:[a-zA-Z0-9_.-[\\]:]+\\Z"
                    )
                ],
            ),
        ),
    ]
